# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 11:17
from __future__ import unicode_literals

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corefiles', '0002_uptodatefile_uptodatefileset'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed', models.DateTimeField(auto_now=True, db_index=True)),
                ('subject', models.CharField(max_length=200)),
                ('semestr', models.SmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corefiles.UpToDateFileSet')),
            ],
            options={
                'default_permissions': (),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
