language: python
sudo: required
dist: trusty

# 1d - 86400
# 1h - 3600
cache:
  timeout: 10000
  pip: true

python:
  - "3.5"
  - "nightly" # currently points to 3.7-dev
matrix:
  allow_failures:
    - python: nightly

# Default:
# install: "pip install -r requirements.txt"

addons:
  apt:
    # sources:
    #   - deadsnakes      # for python 3.5
    packages:
      - nginx
      - supervisor
      - ruby-mustache
      - redis-server

before_script:
  - pwd
  - (cd src; daphne pashinin.asgi:channel_layer --port 8080 -b 127.0.0.1 &)
  - (cd configs; make)
  - ls -la /etc/supervisor/conf.d/
  - ls -la .


# TESTS
# script: nosetests
script:
  - echo "1"
  - curl 127.0.0.1

after_script:
  - git status


notifications:
  email: false
  webhooks:
    urls:
      - https://pashinin.com/travisci
    # on_success: [always|never|change] # default: always
    # on_failure: [always|never|change] # default: always
    # on_start: [always|never|change] # default: never
