sudo: false
language: python
dist: trusty

git:
  depth: 3

# default: 3 min
# 1d - 86400
# 1h - 3600
cache:
  timeout: 10000
  pip: true
  yarn: true
  directories:
    - node_modules
    - $HOME/.yarn-cache

python:
  - "3.5"
  - "3.6"
  # - "nightly" # currently points to 3.7-dev
  # - "pypy3"

env:
  - DEBUG=true DJANGO_SETTINGS_MODULE=pashinin.settings
  - DEBUG=false DJANGO_SETTINGS_MODULE=pashinin.settings


matrix:
  fast_finish: true
  allow_failures:
    - python: pypy

addons:
  postgresql: "9.6"

  apt:
    packages:
      - oracle-java8-set-default  # required by vnu.jar (for html validator)

  # Travis CI will automatically configure the hostnames in /etc/hosts
  # and resolve them to 127.0.0.1.
  hosts:
    - pashinin.com

services:
    - postgresql
    - redis-server

before_install:
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - make requirements
  - pip install coveralls
  - pip install flake8
  - yarn install
  - make render

script:
  - make test-python-style
  - make test-js-style
  - make test

after_success:
  - coveralls

# To use encrypted variables:
#
# sudo gem install travis
# travis encrypt "secret"
# travis encrypt MY_SECRET_ENV=super_secret --add env.matrix
# travis encrypt MY_SECRET_ENV=super_secret -r pashinin-com/parser
notifications:
  email: false
  webhooks:
    urls:
      - https://pashinin.com/_/hooks/travis
    # on_success: [always|never|change] # default: always
    # on_failure: [always|never|change] # default: always
    # on_start: [always|never|change] # default: never
