language: python
python:
  - "3.5"
  - "nightly" # currently points to 3.7-dev
matrix:
  allow_failures:
    - python: nightly

# Default:
# install: "pip install -r requirements.txt"

addons:
  apt:
    # sources:
    #   - deadsnakes      # for python 3.5
    packages:
      - nginx


# command to run tests
# script: nosetests
script: echo "1"
notifications:
  email: false
