language: python
sudo: required
dist: trusty

# 1d - 86400
# 1h - 3600
cache:
  timeout: 10000
  pip: true

python:
  - "3.5"
  - "nightly" # currently points to 3.7-dev
matrix:
  allow_failures:
    - python: nightly

addons:
  apt:
    # sources:
    #   - deadsnakes      # for python 3.5
    packages:
      - nginx
      - supervisor
      # - ruby-mustache
      - ruby
      - redis-server
      - realpath


before_install:
  - sudo gem install mustache

# Default:
# install: "pip install -r requirements.txt"
install:
  - pip install -r requirements.txt
  - pwd
  # - (cd src; daphne pashinin.asgi:channel_layer --port 8080 -b 127.0.0.1 &)
  - (cd configs; make)
  - (cd configs; make links)
  - ls -la /etc/supervisor/conf.d/
  - ls -la /etc/nginx/
  - ls -la .
  - cat /etc/supervisor/conf.d/daphne.conf
  - cat /etc/nginx/nginx.conf
  - sudo service nginx restart
  - sudo service supervisor restart


before_script:
  - ps -ef | grep -v grep | grep nginx
  - ruby -v


# TESTS
# script: nosetests
script:
  - echo "1"
  - curl 127.0.0.1

after_script:
  - git status


after_failure:
  - df -h
  - cat /var/log/nginx/error.log
  - cat /etc/nginx/nginx.conf
  - cat /etc/nginx/sites-enabled/pashinin.com.conf
  - cat /var/log/supervisor/supervisord.log


notifications:
  email: false
  webhooks:
    urls:
      - https://pashinin.com/travisci
    # on_success: [always|never|change] # default: always
    # on_failure: [always|never|change] # default: always
    # on_start: [always|never|change] # default: never
