language: python
sudo: required
dist: trusty

# 1d - 86400
# 1h - 3600
cache:
  timeout: 10000
  pip: true

python:
  - "3.5"
  - "nightly" # currently points to 3.7-dev
matrix:
  allow_failures:
    - python: nightly

addons:
  hosts:
    - pashinin.com
  apt:
    sources:
      #   - deadsnakes      # for python 3.5
      - sourceline: 'ppa:brightbox/ruby-ng'
      - sourceline: 'ppa:nginx/stable'
    packages:
      - nginx-full
      - supervisor
      - ruby2.3
      - ruby-mustache
      - redis-server
      - realpath


before_install:
  - pwd
  - ruby -v
  - nginx -V
  - sudo gem install mustache

# Default:
# install: "pip install -r requirements.txt"
install:
  - pip install -r requirements.txt
  # - (cd src; daphne pashinin.asgi:channel_layer --port 8080 -b 127.0.0.1 &)
  - (cd configs; make)
  - (cd configs; make links)
  - sudo service nginx stop
  - sudo service nginx start
  - sudo service supervisor restart

before_script:
  - ruby -v


# TESTS
# script: nosetests
script:
  # - ps -ef | grep -v grep | grep nginx
  - curl -Is http://pashinin.com | grep "200 OK"

after_script:
  - git status

after_failure:
  - ls -la /etc/supervisor/conf.d/
  - ls -la /etc/nginx/
  - ls -la .
  - df -h
  - sudo cat /var/log/nginx/error.log
  - sudo cat /etc/nginx/nginx.conf
  - sudo cat /etc/supervisor/conf.d/daphne.conf
  - sudo cat /etc/nginx/sites-enabled/pashinin.com.conf
  - sudo cat /var/log/supervisor/supervisord.log
  - sudo supervisorctl status


notifications:
  email: false
  webhooks:
    urls:
      - https://pashinin.com/travisci
    # on_success: [always|never|change] # default: always
    # on_failure: [always|never|change] # default: always
    # on_start: [always|never|change] # default: never
