language: python
python:
  - "3.5"
  - "nightly" # currently points to 3.7-dev
matrix:
  allow_failures:
    - python: nightly

# Default:
# install: "pip install -r requirements.txt"

addons:
  apt:
    # sources:
    #   - deadsnakes      # for python 3.5
    packages:
      - nginx
      - supervisor
      - ruby-mustache

before_script:
  - pwd
  - cd configs && make
  - ls -la /etc/supervisor/conf.d/


# TESTS
# script: nosetests
script: echo "1"

after_script:
  - cat /etc/supervisor/conf.d/daphne.conf


notifications:
  email: false
