sudo: false
language: python
dist: trusty

git:
  depth: 3

# default: 3 min
# 1d - 86400
# 1h - 3600
cache:
  timeout: 10000
  pip: true

python:
  - "3.5"
  # - "nightly" # currently points to 3.7-dev
  # - "pypy3"

env:
  - DJANGO_SETTINGS_MODULE=pashinin.settings

matrix:
  fast_finish: true
  allow_failures:
    - python: pypy

addons:
  postgresql: "9.6"
  hosts:
    - pashinin.com

services:
    - postgresql
    - redis-server

install:
  - make requirements
  - pip install coveralls
  - pip install flake8
  - make render

script:
  - make test-python-style
  - make test-js-style
  - pytest --cov-config .coveragerc --cov src --cov-report term-missing -v --durations=3

after_success:
  - coveralls

# To use encrypted variables:
#
# sudo gem install travis
# travis encrypt "secret"
# travis encrypt MY_SECRET_ENV=super_secret --add env.matrix
# travis encrypt MY_SECRET_ENV=super_secret -r pashinin-com/parser
notifications:
  email: false
  webhooks:
    urls:
      secure: "TvGWdiWk20Fg/d80ys6+Am9K7SmuwQ99WE6/EqW24TuykdjRylzz4gNNecYUz3ABuZAZxPUeoGXk3dDftKfTMs3mV6AJG9kygN2w3BfKMM0BUP4rl1Lzw1lfNbSUWP9i0UCc1PNN03DCHQHVZTgAEKUG7+m2VCwn76Fvh5PoY9cG64mAmlviOr2HL+5GsUDYwnwizhDuZC0SdikfDfxwnlGANQ9LtGjxseh7LYJQ4GU6qvYFKK9zBXNG8p+43/TvDPBgxVctDdo/b72WnqVE+lT37MjoKdSjZyEBk0KICoXY95d50mFU00POvMKMfbfVGXgiEo3CGelElBElTx2EstaNpbhNX55hpO8r7Md1mUbj+fxea50ZBz34Ebys/h8Vzmtz+VwLto9ks7anh7R0JCRKieTrC+wQ9dAoRdARDH9Td+1eg8pqhUjwTyY7imk991qyRcuqVjOlhRBChXxdyskjdetCDsnQvricYTZtdez3gRUHO6GmKdu2sooaQGnWcwA+tmv3lqYhTfZr6kNzQabb1nRKSZ6QxcKao2c6XgR0pQ9MLEMTAnBydsYzvChthOiDsG6nJW1msERxClawlUS1q3rwoaXz09OagS7FOkHS0YzhGroFH9anVvyy+rNWLc+MeHniQUaF93gveXoggZHsfGcYv4JIAENYJBhNcoU="
    # - https://pashinin.com/_/hooks/travis
    # on_success: [always|never|change] # default: always
    # on_failure: [always|never|change] # default: always
    # on_start: [always|never|change] # default: never
