# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Google displays first 50-60 characters of a title tag', max_length=100),
        ),
    ]
