# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_auto_20170214_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.CharField(blank=True, help_text='ВУЗ, факультет, экзамен / рубежный контроль', max_length=130, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='task',
            name='taken_from',
            field=models.IntegerField(choices=[(0, 'No source'), (1, 'ФИПИ, открытый банк заданий'), (2, 'из Бауманки')], default=0, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='task',
            name='added',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Added'),
        ),
        migrations.AlterField(
            model_name='task',
            name='published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Google displays first 50-60 characters of a title tag', max_length=100, verbose_name='Title'),
        ),
    ]
