# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_auto_20170215_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Тема задачи или уникальная метка (системы счисления, исполнитель РОБОТ)', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='taken_from',
            field=models.IntegerField(choices=[(0, 'No source'), (1, 'ФИПИ, открытый банк заданий'), (2, 'из Бауманки'), (3, 'Типовые тестовые задания (ИНФ), 2017, Лещинер В.Р.')], default=0, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='edu.Tag'),
        ),
    ]
