# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_auto_20170217_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='hint',
            field=models.CharField(blank=True, help_text='Чуть подробднее о задаче(Дана таблица, найти то-то)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='edu.Tag', verbose_name='Tags'),
        ),
    ]
