# Generated by Django 2.0 on 2018-01-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0014_auto_20171212_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: "Bauman MSTU"', max_length=130)),
            ],
        ),
    ]
