# Generated by Django 2.0 on 2018-01-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0015_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='location_str',
            field=models.CharField(blank=True, help_text='Example: "Россия, Москва"', max_length=130, null=True),
        ),
    ]
