# Generated by Django 2.0 on 2018-01-05 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0016_organization_location_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=130)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Organization')),
            ],
        ),
    ]
