# Generated by Django 2.0 on 2018-01-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0017_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='код полностью (MPCS 51036)', max_length=10, null=True)),
                ('title', models.CharField(help_text='Java Programming', max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='код полностью (ИУ2)', max_length=10, null=True)),
                ('title', models.CharField(max_length=130)),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(help_text='ИУ', max_length=10),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='title',
            field=models.CharField(help_text='Информатики и систем управления', max_length=130),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Organization'),
        ),
    ]
