# Generated by Django 2.0 on 2018-01-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0018_auto_20180106_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code_slug',
            field=models.CharField(blank=True, help_text='url-valid code', max_length=15, null=True),
        ),
    ]
