# Generated by Django 2.0 on 2018-01-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0019_department_code_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code_slug',
            field=models.CharField(blank=True, help_text='url-valid code', max_length=50, null=True),
        ),
    ]
