# Generated by Django 2.0 on 2018-01-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0020_auto_20180106_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(help_text='Семестр 1', max_length=100)),
            ],
        ),
    ]
