# Generated by Django 2.0 on 2018-01-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0021_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='practice_comments_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
