# Generated by Django 2.0 on 2018-01-09 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0022_department_practice_comments_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.Department'),
        ),
    ]
