# Generated by Django 2.0 on 2018-01-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0023_period_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('name', 'department')},
        ),
    ]
