# Generated by Django 2.0 on 2018-01-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0024_auto_20180109_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Published'),
        ),
    ]
