# Generated by Django 2.0.1 on 2018-01-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0025_faculty_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(help_text='ИУ', max_length=10, verbose_name='Код факультета'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='title',
            field=models.CharField(help_text='Информатики и систем управления', max_length=130, verbose_name='Название факультета'),
        ),
    ]
