# Generated by Django 2.0.1 on 2018-01-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0027_auto_20180111_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='botva_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
