# Generated by Django 2.0.1 on 2018-01-11 13:26

import core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0028_department_botva_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='added',
            field=models.DateTimeField(db_index=True, default=core.now),
        ),
    ]
