# Generated by Django 2.0.1 on 2018-01-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0029_faculty_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='added',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
