# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='added',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='changed',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
