version: '2'
services:
  web:
    stdin_open: true
    tty: true
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ../:/var/www/pashinin.com
    depends_on:
      - redis
  redis:
    image: redis
