version: '2'
services:
  web:
    # fixes: cannot open /dev/fuse (Operation not permitted)
    # --cap-add SYS_ADMIN --device /dev/fuse
    # trying this:
    privileged: true
    # with these not working yet:
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse

    command: sleep infinity

    # these 2 are for getting output from commands like djangos debug server
    # stdin_open: true
    # tty: true

    build: .
    ports:
      - "80:8000"
    volumes:
      - ../:/var/www/pashinin.com
    depends_on:
      - redis
      - db
      - dbinit
      - migration
    # command: python manage.py migrate
    links:
      - db
    extra_hosts:
      - "pashinin.com:10.254.239.1"
  redis:
    image: redis
    # restart: always
  db:
    image: postgres
    # volumes:
    #   - ../:/var/www/pashinin.com
    # environment:
    #   POSTGRES_USER: pashinin
    #   POSTGRES_PASSWORD: superpass

  dbinit:
    image: postgres
    # image: python:3-onbuild
    working_dir: /var/www/pashinin.com/configs
    command: psql -h db -U postgres -a -f tmp/dbinit.sql
    volumes:
      - ../:/var/www/pashinin.com
    # links:
    #   - db
    depends_on:
      - db

  migration:
    build: .
    working_dir: /var/www/pashinin.com/src
    command: ../configs/migrations.sh
    user: www-data
    volumes:
      - ../:/var/www/pashinin.com
    # links:
    #   - db
    depends_on:
      - dbinit


# restart: on-failure:10
