#
# rparser needs to be recompiled exactly for Alpine (musl) to load
#
FROM python:3.6-alpine3.6

RUN apk update && \
    apk add --no-cache postgresql-dev jpeg-dev zlib-dev libpq libxslt-dev libxslt python3-dev \
    libc-dev linux-headers libxml2 libxml2-dev gcc git g++ libc6-compat libmagic make libffi-dev \
    musl-dev

COPY requirements.txt /tmp/
RUN pip install pip -U
RUN pip install psycopg2 -U
RUN pip install ipdb -U
RUN pip install -r /tmp/requirements.txt --no-cache-dir && \
    rm -rf /tmp/src && \
    rm -rf /var/cache/apk/*

RUN mkdir /mnt/files
RUN chmod 777 /mnt/files
WORKDIR /var/www/project/src
EXPOSE 8000
