version: '2'
services:
  web:
    stdin_open: true
    tty: true
    build: .
    ports:
      - "80:8000"
    volumes:
      - ../:/var/www/pashinin.com
    depends_on:
      - redis
      - db
      - dbinit
      - migration
    # command: python manage.py migrate
    links:
      - db
  redis:
    image: redis
    # restart: always
  db:
    image: postgres
    # volumes:
    #   - ../:/var/www/pashinin.com
    # environment:
    #   POSTGRES_USER: pashinin
    #   POSTGRES_PASSWORD: superpass

  dbinit:
    image: postgres
    # image: python:3-onbuild
    working_dir: /tmp
    command: psql -h db -U postgres -a -f /var/www/pashinin.com/configs/tmp/dbinit.sql
    volumes:
      - ../:/var/www/pashinin.com
    # links:
    #   - db
    depends_on:
      - db

  migration:
    build: .
    working_dir: /var/www/pashinin.com/src
    command: ../configs/migrations.sh
    volumes:
      - ../:/var/www/pashinin.com
    # links:
    #   - db
    depends_on:
      - dbinit


# restart: on-failure:10
