# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ege',
            name='type',
            field=models.IntegerField(choices=[(0, 'ЕГЭ (11 кл)'), (1, 'ОГЭ (9 кл)')], default=0, verbose_name='Тип экзамена'),
        ),
    ]
