# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0003_auto_20170125_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ege',
            options={'verbose_name': 'ЕГЭ / ОГЭ', 'verbose_name_plural': 'ЕГЭ / ОГЭ'},
        ),
    ]
