# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0004_auto_20170125_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('name', 'slug')]),
        ),
    ]
