# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_auto_20170217_1434'),
        ('ege', '0005_auto_20170129_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '1 единственная задача'), (1, '1 задача из N на выбор')], default=0, verbose_name='Нужно решить')),
                ('order', models.IntegerField(verbose_name='Номер задачи в экзамене, например от 1 до 27')),
                ('tags', models.ManyToManyField(help_text='Все тэги, которые подходят для этой задачи в этом экзамене', related_name='ege_tasks', to='edu.Category', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='ege',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='exams', to='ege.Task'),
        ),
    ]
