# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0006_auto_20170217_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EGE',
            new_name='Exam',
        ),
    ]
