# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0008_auto_20170218_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.CharField(help_text='Отображаемая тема этой задачи экзамена, если не указана, то будут использованы тэги', max_length=50, null=True, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ege.Exam'),
        ),
    ]
