# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0009_auto_20170218_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.CharField(blank=True, help_text='Отображаемая тема этой задачи экзамена, если не указана, то будут использованы тэги', max_length=150, null=True, verbose_name='Тема'),
        ),
    ]
