# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0010_auto_20170218_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='time',
            field=models.IntegerField(default=0, help_text='Отведённое время, мин'),
        ),
    ]
