# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0012_auto_20170511_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
    ]
