# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0014_auto_20170514_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Экзамен (ЕГЭ / ОГЭ)', 'verbose_name_plural': 'Экзамены (ЕГЭ / ОГЭ)'},
        ),
    ]
