# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161101_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.AlterIndexTogether(
            name='file',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='file',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
