# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 14:38
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161101_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_comment_parent', to='core.Comment', verbose_name='Parent element')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='example.org, host.example.org', max_length=260)),
                ('is_domain', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Hostnames',
                'verbose_name': 'Hostname',
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inet', netfields.fields.InetAddressField(max_length=39)),
                ('open_ports', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name_plural': 'IP-addresses',
                'verbose_name': 'IP',
            },
        ),
    ]
