# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment_hostname_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('finished', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sha1', models.CharField(editable=False, max_length=40, unique=True)),
                ('log', models.TextField()),
            ],
        ),
    ]
