# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteupdate',
            name='finished',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteupdate',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
