# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170119_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteupdate',
            options={'verbose_name': 'Site update', 'verbose_name_plural': 'Site updates'},
        ),
    ]
