# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170127_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteupdate',
            name='commit_message',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='siteupdate',
            name='commit_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='siteupdate',
            name='travis_raw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
