# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170127_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(related_name='permissions', to='auth.Permission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='auth.Group'),
        ),
    ]
