# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170201_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='permissions', to='auth.Permission'),
        ),
    ]
