# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20170907_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, default='', help_text='This is an unique identifier, not actual username. Can be a session key for temporary users', max_length=200, null=True),
        ),
    ]
