# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_browser_on_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_from_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
