# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170912_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone_str',
            field=models.CharField(db_index=True, default='UTC', max_length=50),
        ),
    ]
