# Generated by Django 2.0.1 on 2018-01-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20171212_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
