# Generated by Django 2.0.2 on 2018-03-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20180306_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
