# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 21:33
from __future__ import unicode_literals

import core
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed', models.DateTimeField(auto_now=True, db_index=True)),
                ('basename', models.CharField(blank=True, max_length=200, null=True)),
                ('sha1', models.CharField(editable=False, max_length=40, unique=True)),
                ('size', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('content_type', models.IntegerField(blank=True, choices=[(0, 'application'), (1, 'audio'), (2, 'example'), (3, 'image'), (4, 'message'), (5, 'model'), (6, 'multipart'), (7, 'text'), (8, 'video')], null=True)),
                ('content_subtype', models.CharField(blank=True, max_length=96, null=True)),
                ('public', models.BooleanField(default=False, help_text='Anyone can access this file')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('uploader', models.ForeignKey(blank=True, db_column='uploader', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'default_permissions': (),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='%Y/%m/%d')),
                ('date_uploaded', models.DateTimeField(default=core.now)),
                ('sha1', models.CharField(blank=True, editable=False, max_length=40, null=True, verbose_name='SHA1')),
                ('uploader', models.ForeignKey(blank=True, db_column='uploader', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded file',
                'verbose_name_plural': 'Uploaded files',
            },
        ),
        migrations.AlterIndexTogether(
            name='file',
            index_together=set([('content_type', 'content_subtype')]),
        ),
    ]
