# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corefiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpToDateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed', models.DateTimeField(auto_now=True, db_index=True)),
                ('basename', models.CharField(blank=True, max_length=200, null=True)),
                ('current_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corefiles.File')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UpToDateFileSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed', models.DateTimeField(auto_now=True, db_index=True)),
                ('files', models.ManyToManyField(to='corefiles.UpToDateFile')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
