# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corefiles', '0002_uptodatefile_uptodatefileset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='BaseFile',
        ),
    ]
