# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corefiles', '0003_auto_20170907_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uptodatefile',
            old_name='basename',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='basefile',
            name='basename',
        ),
        migrations.RemoveField(
            model_name='basefile',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='basefile',
            name='public',
        ),
        migrations.RemoveField(
            model_name='basefile',
            name='uploader',
        ),
        migrations.AlterField(
            model_name='uptodatefileset',
            name='files',
            field=models.ManyToManyField(to='corefiles.BaseFile'),
        ),
    ]
