# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corefiles', '0004_auto_20170908_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uptodatefile',
            old_name='current_file',
            new_name='basefile',
        ),
        migrations.AlterField(
            model_name='basefile',
            name='content_subtype',
            field=models.CharField(blank=True, editable=False, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='basefile',
            name='content_type',
            field=models.IntegerField(blank=True, choices=[(0, 'application'), (1, 'audio'), (2, 'example'), (3, 'image'), (4, 'message'), (5, 'model'), (6, 'multipart'), (7, 'text'), (8, 'video')], editable=False, null=True),
        ),
    ]
