# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corefiles', '0005_auto_20170908_2251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpToDateFile',
            new_name='File',
        ),
    ]
