# Generated by Django 2.0 on 2017-12-12 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corefiles', '0007_auto_20170908_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='basefile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corefiles.BaseFile'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploader',
            field=models.ForeignKey(blank=True, db_column='uploader', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
