# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_auto_20170305_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'назначено время'), (1, 'проведено'), (2, 'пропуск (предупредили за 24 часа)'), (3, 'пропуск (без предупреждения)')], default=0, verbose_name='Статус')),
                ('start', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('end', models.DateTimeField(db_index=True)),
                ('comment', models.TextField(blank=True, help_text='Что было на этом занятии?', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('learn', models.TextField(blank=True, help_text='С чем помочь?', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pashinin.Student'),
        ),
    ]
