# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pashinin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='start',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
