# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pashinin', '0002_auto_20170305_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='scheduled',
            field=models.BooleanField(default=False, help_text='Повторяется ли это занятие? Время берется из поля start.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
