# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pashinin', '0003_auto_20170314_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.IntegerField(choices=[(0, 'назначено время'), (1, 'проведено'), (2, 'пропуск (предупредили минимум за 24 часа)'), (3, 'пропуск (без предупреждения или менее чем за 24ч)')], default=0, verbose_name='Статус'),
        ),
    ]
