# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pashinin', '0007_auto_20170829_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='courselead',
            unique_together=set([('course', 'session_key', 'student')]),
        ),
    ]
