# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 09:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pashinin', '0010_courselead_status'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='courselead',
        #     name='session_key',
        # ),
        migrations.AlterUniqueTogether(
            name='courselead',
            unique_together=set([('course', 'student')]),
        ),
    ]
