# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pashinin', '0011_auto_20170907_1240'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='courselead',
        #     name='session_key',
        #     field=models.CharField(blank=True, max_length=150, null=True),
        # ),
    ]
