# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pashinin', '0012_courselead_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselead',
            name='session_key',
        ),
    ]
