# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pashinin', '0013_remove_courselead_session_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courselead',
            unique_together=set([]),
        ),
    ]
