# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pashinin', '0015_qa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qa',
            options={'ordering': ('order',), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
