# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pashinin', '0016_auto_20171021_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(help_text='python-base, ege-inf, lpic-1, ...', max_length=60, unique=True),
        ),
    ]
