# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pashinin', '0017_auto_20171026_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='logo_sha1',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
